version: '3'

services:
  web:
    image: front-appprocesso
    build: ./frontend
    depends_on:
      - api
    ports:
      - 3000:3000
    networks:
      - network-backend
  api:
    image: backend-appprocesso
    build: ./backend
    ports:
      - 3333:3333
    networks:
      - network-backend

networks:
  network-backend: